{
  description = "Austin's NixOS 26.05 config for HP Laptop 14-ep0xxx (shitbox)";

  # NOTE:
  #  We intentionally do NOT set experimental-features / auto-optimise-store
  #  in nixConfig. Those belong in the *system* nix.settings (see
  #  modules/base.nix); putting them here only affects evaluation of this
  #  flake and triggers a trust prompt.

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Optional: unstable channel for cherry-picking newer Mesa/gamescope etc.
    # without moving the whole system off 26.05. Expose it in a module via
    # `nixpkgs.overlays` as `pkgs.unstable.<pkg>`. Only add when a concrete
    # package forces the need.
    # nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      ...
    }@inputs:
    let
      system = "x86_64-linux";
      inherit (nixpkgs) lib;
      pkgs = nixpkgs.legacyPackages.${system};

      # hardware-configuration.nix is regenerated by nixos-generate-config,
      # which would undo any formatting/lint fixes, so it is exempt.
      generated = "hardware-configuration.nix";
      formatter = pkgs.nixfmt-tree.override {
        settings.global.excludes = [ generated ];
      };
    in
    {
      # `nix fmt` formats the whole tree.
      formatter.${system} = formatter;

      # `nix flake check` fails if any of these find a problem.
      checks.${system} = {
        format = pkgs.runCommand "check-format" { nativeBuildInputs = [ formatter ]; } ''
          cp -r ${self} src && chmod -R u+w src && cd src
          treefmt --ci --tree-root .
          touch $out
        '';
        statix = pkgs.runCommand "check-statix" { nativeBuildInputs = [ pkgs.statix ]; } ''
          cd ${self}
          statix check .
          touch $out
        '';
        deadnix = pkgs.runCommand "check-deadnix" { nativeBuildInputs = [ pkgs.deadnix ]; } ''
          cd ${self}
          deadnix --fail --exclude ${generated} -- .
          touch $out
        '';
      };

      # Handy dev shell: `nix develop` gives you the lint/format tooling.
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          formatter
          pkgs.statix
          pkgs.deadnix
          pkgs.nh
        ];
      };

      nixosConfigurations.shitbox = lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs; };

        modules = [
          ./hosts/shitbox/configuration.nix

          home-manager.nixosModules.home-manager
          {
            home-manager = {
              useGlobalPkgs = true;
              useUserPackages = true;
              users.austin = import ./home/austin/home.nix;
              # Keep a timestamped backup instead of failing when HM would
              # clobber an existing dotfile.
              backupFileExtension = "hm-bak";
            };
          }
        ];
      };
    };
}
