{
  description = "Austin's NixOS 26.05 config for HP Laptop 14-ep0xxx (shitbox)";

  # NOTE:
  #  We intentionally do NOT set experimental-features in nixConfig. Nix
  #  settings belong in the *system* nix.settings (see
  #  modules/base.nix); putting them here only affects evaluation of this
  #  flake and triggers a trust prompt.

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    home-manager.url = "github:nix-community/home-manager/release-26.05";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    # Plasma/KDE app settings as Home Manager options (home/austin/plasma.nix).
    # Pinned to a commit: plasma-manager has no stable release branch, so
    # following its latest code let `update` pull in changed options or
    # behavior. To move it, replace the commit with a newer one from
    # github.com/nix-community/plasma-manager/commits and run `rebuild`.
    plasma-manager = {
      url = "github:nix-community/plasma-manager/a19a2a029fa180911bd89c554dca1616e10f4c1d";
      inputs.nixpkgs.follows = "nixpkgs";
      inputs.home-manager.follows = "home-manager";
    };

    # Declarative Flatpak apps and remotes (modules/desktop.nix). `latest`
    # is the project's tag for its newest release.
    nix-flatpak.url = "github:gmodena/nix-flatpak/?ref=latest";

    # Prebuilt nix-index database: "command not found" suggests the package,
    # and `, <cmd>` runs it without installing (home/austin/bling.nix).
    nix-index-database = {
      url = "github:nix-community/nix-index-database";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Optional: unstable channel for cherry-picking newer Mesa/gamescope etc.
    # without moving the whole system off 26.05. Expose it in a module via
    # `nixpkgs.overlays` as `pkgs.unstable.<pkg>`. Only add when a concrete
    # package forces the need.
    # nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs =
    {
      self,
      nixpkgs,
      home-manager,
      plasma-manager,
      nix-flatpak,
      nix-index-database,
      ...
    }:
    let
      system = "x86_64-linux";
      inherit (nixpkgs) lib;
      pkgs = nixpkgs.legacyPackages.${system};

      # Config version; see "Versions" in README.md for when to bump it.
      version = "v61";

      # hardware-configuration.nix is regenerated by nixos-generate-config,
      # which would undo any formatting/lint fixes, so it is exempt.
      generated = "hosts/shitbox/hardware-configuration.nix";
      formatter = pkgs.nixfmt-tree.override {
        settings.global.excludes = [ generated ];
      };

      # Everything shitbox is built from; shared by nixosConfigurations.shitbox
      # and the VM boot test (tests/boot.nix).
      shitboxModules = [
        ./hosts/shitbox/configuration.nix

        # Git commit the system was built from (with -dirty for uncommitted
        # changes); shown by `nixos-version --configuration-revision`.
        # The config version is added to the system label, so it shows in
        # the boot menu and the system's store path (and thus in the MOTD
        # and fastfetch; see home/austin/bling.nix).
        {
          system.configurationRevision = self.rev or self.dirtyRev or null;
          system.nixos.tags = [ version ];
        }

        nix-flatpak.nixosModules.nix-flatpak

        home-manager.nixosModules.home-manager
        {
          home-manager = {
            useGlobalPkgs = true;
            useUserPackages = true;
            sharedModules = [
              plasma-manager.homeModules.plasma-manager
              nix-index-database.homeModules.nix-index
            ];
            users.austin = import ./home/austin/home.nix;
            # When HM would clobber an unmanaged dotfile, move it to
            # <file>.hm-bak instead of failing activation. The name is
            # fixed, so overwriteBackup replaces an older .hm-bak rather
            # than failing the second time.
            backupFileExtension = "hm-bak";
            overwriteBackup = true;
          };
        }
      ];
    in
    {
      # `nix fmt` formats the whole tree.
      formatter.${system} = formatter;

      # `nix flake check` fails if any of these find a problem.
      checks.${system} = {
        format = pkgs.runCommand "check-format" { nativeBuildInputs = [ formatter ]; } ''
          cp -r ${self} src && chmod -R u+w src && cd src
          treefmt --ci --tree-root .
          touch $out
        '';
        statix = pkgs.runCommand "check-statix" { nativeBuildInputs = [ pkgs.statix ]; } ''
          cd ${self}
          statix check .
          touch $out
        '';
        deadnix = pkgs.runCommand "check-deadnix" { nativeBuildInputs = [ pkgs.deadnix ]; } ''
          cd ${self}
          deadnix --fail --exclude ${generated} -- .
          touch $out
        '';
        # The README must advertise the version the flake builds.
        version = pkgs.runCommand "check-version" { } ''
          grep -q '^\*\*Current version: ${version}\*\*' ${self}/README.md \
            || { echo "README.md 'Current version' doesn't say ${version}" >&2; exit 1; }
          touch $out
        '';

        # Boots the system in a VM and checks that it works (tests/boot.nix).
        boot = lib.nixos.runTest {
          hostPkgs = pkgs;
          imports = [
            (import ./tests/boot.nix {
              modules = shitboxModules;
              inherit version;
            })
          ];
        };
      };

      # The installer ISO (hosts/installer/configuration.nix):
      #   nix build .#installer-iso    ->  result/iso/shitbox-installer-vN.iso
      packages.${system}.installer-iso = self.nixosConfigurations.installer.config.system.build.isoImage;

      # Handy dev shell: `nix develop` gives you the lint/format tooling.
      devShells.${system}.default = pkgs.mkShell {
        packages = [
          formatter
          pkgs.statix
          pkgs.deadnix
        ];
      };

      nixosConfigurations.shitbox = lib.nixosSystem {
        inherit system;
        modules = shitboxModules;
      };

      # Live Plasma USB that installs the shitbox config above (see
      # hosts/installer/configuration.nix). Built as packages.installer-iso.
      nixosConfigurations.installer = lib.nixosSystem {
        inherit system;
        specialArgs = { inherit self version; };
        modules = [ ./hosts/installer/configuration.nix ];
      };
    };
}
